CC = gcc
AS = as
CFLAGS = -m32 -Wall -O0 -fno-stack-protector
ASFLAGS = --32

.PHONY: all clean

all: run.hex

run.hex: run.o
	./extract-code.sh run.o run.hex

run.o: run_interceptor1.o $(INTERCEPTOR_OBJ)
	ld -e 0 -melf_i386 $^ -o $@

run_interceptor1.s: run_interceptor.s
	cpp -DREL_PLT=$(REL_PLT) -DDYN_SYM=$(DYN_SYM) -DDYN_STR=$(DYN_STR) $< -o $@

clean:
	rm -f *.o *~ *.hex run_interceptor1.s
