AS = as
ASFLAGS = --32

.PHONY: all clean

all: all.out

all.out: run_interceptor1.o $(INTERCEPTOR_OBJ)
	ld -e 0 -melf_i386 $^ -o $@

run_interceptor1.s: run_interceptor_x86.s
	cpp -DPLT0=$(PLT0) -DREL_PLT=$(REL_PLT) -DDYN_SYM=$(DYN_SYM) -DDYN_STR=$(DYN_STR) -DENTRY=$(ENTRY) -DADDITIONAL_DATA=$(ADDITIONAL_DATA) -DVA=$(VA) $< -o $@

clean:
	rm -f *.o *~ run_interceptor1.s all.out
