AS = as
ASFLAGS = --64

.PHONY: all clean $(INTERCEPTOR_OBJ)

all: all.out

all.out: run_interceptor1.o gen/src/utils.o gen/src/syscalls.o $(INTERCEPTOR_OBJ)
	ld $^ -o $@

run_interceptor1.s: gen/asm/run_interceptor_x64.s
	cpp -DPLT0=$(PLT0) -DREL_PLT=$(REL_PLT) -DDYN_SYM=$(DYN_SYM) -DDYN_STR=$(DYN_STR) -DENTRY=$(ENTRY) -DADDITIONAL_DATA=$(ADDITIONAL_DATA) $< -o $@

clean:
	rm -f *.o *~ run_interceptor1.s all.out
